name: discord message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: webhook-notifications
        id: webhook-notifications
        uses: aledamen/webhook-notifications@v0.1
        with:
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
